stages:
  - deploy

deploy:
  stage: deploy
  only:
    - prod
  script:
    - rsync -avr ./ $DEPLOY_PATH --exclude '.git'
    - cd $DEPLOY_PATH
    - cnpm install
    - sudo pm2 stop mock
    - sudo pm2 start ./bin/www --name mock