stages:
  - deploy

deploy:
  stage: deploy
  only:
    - prod
  script:
    - rsync -avr ./ $DEPLOY_PATH --exclude '.git'
    - cd $DEPLOY_PATH
    - cnpm install
    - pm2 restart ./bin/www --name mock