stages:
  - deploy

deploy:
  stage: deploy
  only:
    - tags
  script:
    - sudo rsync -avr ./ $DEPLOY_PATH --exclude '.git'
    - cd $DEPLOY_PATH
    - cnpm install
    - export PM2_HOME=/root/.pm2
    - sudo pm2 startOrRestart ./ecosystem.config.js